import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  {
    // next-env.d.ts is regenerated by Next on every build, so linting it just
    // produces an error nobody can fix.
    ignores: [
      '.next/**',
      'node_modules/**',
      'drizzle/**',
      'coverage/**',
      'scripts/**',
      '.outbox/**',
      'next-env.d.ts',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      // Unused arguments are often there to document a signature; requiring a
      // leading underscore keeps that legible without silencing real dead code.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
      // `any` defeats the point of the payload schema, which is the one place
      // this product cannot afford to be loose about types.
      '@typescript-eslint/no-explicit-any': 'error',
    },
  },
];

export default config;
